//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQ_PO_STATUS
    {
        public int POID { get; set; }
        public System.DateTime SetDate { get; set; }
        public int StatusID { get; set; }
        public string Note { get; set; }
    
        public virtual ACQ_PO ACQ_PO { get; set; }
        public virtual ACQ_STATUS ACQ_STATUS { get; set; }
    }
}
