//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQ_ONLOAN_INLIST_INVENT
    {
        public int ID { get; set; }
        public string CopyNumber { get; set; }
        public int InvID { get; set; }
        public int InventoryTime { get; set; }
    }
}
