//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANDOC_IN
    {
        public string So_the { get; set; }
        public string Ngay_cap { get; set; }
        public string Ngay_het_han { get; set; }
        public string Ho_ten { get; set; }
        public string Ngay_sinh { get; set; }
        public string Lop { get; set; }
        public string Khoa { get; set; }
    }
}
