//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_DIC_LANGUAGE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_DIC_LANGUAGE()
        {
            this.ACQ_ITEM = new HashSet<ACQ_ITEM>();
            this.ITEM_LANGUAGE = new HashSet<ITEM_LANGUAGE>();
        }
    
        public int ID { get; set; }
        public string AccessEntry { get; set; }
        public string DisplayEntry { get; set; }
        public Nullable<int> DicItemID { get; set; }
        public string ISOCode { get; set; }
        public string NameViet { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQ_ITEM> ACQ_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_LANGUAGE> ITEM_LANGUAGE { get; set; }
    }
}
