//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EDATA_FILE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_EDATA_FILE()
        {
            this.CAT_EDATA_METADATA = new HashSet<CAT_EDATA_METADATA>();
            this.EDELIV_REQUEST = new HashSet<EDELIV_REQUEST>();
        }
    
        public int ID { get; set; }
        public int FileSize { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public string FieldCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string URL { get; set; }
        public string PhysicalPath { get; set; }
        public bool Existed { get; set; }
        public string FileLocation { get; set; }
        public int SecretLevel { get; set; }
        public int DownloadTimes { get; set; }
        public int MediaType { get; set; }
        public bool Locked { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string LockedBy { get; set; }
        public string LastModifiedBy { get; set; }
        public int ModifiedTimes { get; set; }
        public int Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> CollectionID { get; set; }
        public bool Free { get; set; }
        public string FileName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string Pagination { get; set; }
        public string FileFormat { get; set; }
    
        public virtual ACQ_CURRENCY ACQ_CURRENCY { get; set; }
        public virtual CAT_EDATA_COLLECTION CAT_EDATA_COLLECTION { get; set; }
        public virtual ITEM ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_EDATA_METADATA> CAT_EDATA_METADATA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDELIV_REQUEST> EDELIV_REQUEST { get; set; }
    }
}
