//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EDATA_METADATA
    {
        public int objID { get; set; }
        public int MetadataID { get; set; }
        public string DisplayEntry { get; set; }
        public string AccessEntry { get; set; }
        public int ID { get; set; }
    
        public virtual CAT_EDATA_FILE CAT_EDATA_FILE { get; set; }
        public virtual CAT_EDATA_METADATA_DEFIN CAT_EDATA_METADATA_DEFIN { get; set; }
    }
}
