//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_LOAN
    {
        public int ID { get; set; }
        public int LoanTypeID { get; set; }
        public Nullable<byte> LoanMode { get; set; }
        public string CopyNumber { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Note { get; set; }
        public short RenewCount { get; set; }
        public int PatronID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<System.DateTime> RecallDate { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Serial { get; set; }
    
        public virtual CIR_LOAN_TYPE CIR_LOAN_TYPE { get; set; }
        public virtual CIR_PATRON CIR_PATRON { get; set; }
        public virtual HOLDING_LOCATION HOLDING_LOCATION { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
