//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_FINE
    {
        public int ID { get; set; }
        public string PatronCode { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Reason { get; set; }
        public float Rate { get; set; }
        public string Currency { get; set; }
    
        public virtual ACQ_CURRENCY ACQ_CURRENCY { get; set; }
    }
}
