//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_PHOTOCOPY_PRICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIR_PHOTOCOPY_PRICE()
        {
            this.CIR_PHOTOCOPY_REQUEST = new HashSet<CIR_PHOTOCOPY_REQUEST>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public Nullable<decimal> PricePerPage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIR_PHOTOCOPY_REQUEST> CIR_PHOTOCOPY_REQUEST { get; set; }
    }
}
