//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_PHOTOCOPY_REQUEST
    {
        public int ID { get; set; }
        public int TypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal PaidAmount { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Inputer { get; set; }
        public bool Done { get; set; }
        public int PageCount { get; set; }
        public string PageDetail { get; set; }
        public string PatronCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CopyNumber { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual CIR_PHOTOCOPY_PRICE CIR_PHOTOCOPY_PRICE { get; set; }
    }
}
