//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSIFICATION_FIELD
    {
        public int ID { get; set; }
        public bool Mandatory { get; set; }
        public int FunctionID { get; set; }
        public bool Coded { get; set; }
        public Nullable<int> Length { get; set; }
        public string Indicators { get; set; }
        public string VietIndicators { get; set; }
        public int FieldTypeID { get; set; }
        public bool Repeatable { get; set; }
        public int LinkTypeID { get; set; }
        public string FieldCode { get; set; }
        public int BlockID { get; set; }
        public string FieldName { get; set; }
        public string VietFieldName { get; set; }
        public Nullable<int> DicID { get; set; }
    }
}
