//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDELIV_REQUEST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EDELIV_REQUEST()
        {
            this.EDELIV_PAYMENT = new HashSet<EDELIV_PAYMENT>();
        }
    
        public int RequestID { get; set; }
        public string Note { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public Nullable<System.DateTime> DeniedDate { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FileID { get; set; }
        public Nullable<int> ModeID { get; set; }
        public Nullable<int> RequestGroupID { get; set; }
        public bool Alert { get; set; }
        public string TempFileLoc { get; set; }
        public Nullable<System.DateTime> TempFileDate { get; set; }
    
        public virtual CAT_EDATA_FILE CAT_EDATA_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EDELIV_PAYMENT> EDELIV_PAYMENT { get; set; }
        public virtual EDELIV_REQUEST_MODE EDELIV_REQUEST_MODE { get; set; }
        public virtual EDELIV_STATUS EDELIV_STATUS { get; set; }
        public virtual EDELIV_USER EDELIV_USER { get; set; }
    }
}
