//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FPT_CATA_FILE_NEW
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
