//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_Z3950_SERVERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILL_Z3950_SERVERS()
        {
            this.ILL_Z3950_DBS = new HashSet<ILL_Z3950_DBS>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public Nullable<int> Port { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public bool PreferredLender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_Z3950_DBS> ILL_Z3950_DBS { get; set; }
    }
}
