//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_SERVICE_TYPES
    {
        public byte ID { get; set; }
        public string ServiceType { get; set; }
        public string ServiceDisplay { get; set; }
    }
}
