//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_OUTGOING_REQUESTS_RETINF
    {
        public int ID { get; set; }
        public string PostDelivName { get; set; }
        public string PostDelivXAddress { get; set; }
        public string PostDelivStreet { get; set; }
        public string PostDelivBox { get; set; }
        public string PostDelivCity { get; set; }
        public string PostDelivRegion { get; set; }
        public Nullable<byte> PostDelivCountry { get; set; }
        public string PostDelivCode { get; set; }
    }
}
