//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SER_ARTICLE
    {
        public int ID { get; set; }
        public int IssueID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Page { get; set; }
        public string Note { get; set; }
        public string Subject { get; set; }
        public byte[] Ts { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public string ImageURL { get; set; }
    
        public virtual SER_ISSUE SER_ISSUE { get; set; }
    }
}
