//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SER_ROUTING
    {
        public Nullable<int> POID { get; set; }
        public int LocationID { get; set; }
        public System.DateTime AppliedDate { get; set; }
        public int Copies { get; set; }
        public int ItemID { get; set; }
        public int ID { get; set; }
    
        public virtual ACQ_PO ACQ_PO { get; set; }
        public virtual HOLDING_LOCATION HOLDING_LOCATION { get; set; }
        public virtual ITEM ITEM { get; set; }
    }
}
