//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPAC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_LOG
    {
        public long ID { get; set; }
        public string FileName { get; set; }
        public string Workstation { get; set; }
        public string User { get; set; }
        public int EventGroupID { get; set; }
        public string Event { get; set; }
        public System.DateTime LogTime { get; set; }
    
        public virtual SYS_EVENT_GROUP SYS_EVENT_GROUP { get; set; }
    }
}
