//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQ_BUDGET_ACCUMULATE
    {
        public int ID { get; set; }
        public int BudgetID { get; set; }
        public int InYear { get; set; }
        public int InMonth { get; set; }
        public decimal Balance { get; set; }
    
        public virtual ACQ_BUDGET ACQ_BUDGET { get; set; }
    }
}
