//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQ_PO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACQ_PO()
        {
            this.ACQ_BUDGET_CREDIT = new HashSet<ACQ_BUDGET_CREDIT>();
            this.ACQ_BUDGET_DEBIT = new HashSet<ACQ_BUDGET_DEBIT>();
            this.ACQ_ITEM = new HashSet<ACQ_ITEM>();
            this.ACQ_PO_STATUS = new HashSet<ACQ_PO_STATUS>();
            this.HOLDINGs = new HashSet<HOLDING>();
            this.SER_ITEM = new HashSet<SER_ITEM>();
            this.SER_ROUTING = new HashSet<SER_ROUTING>();
            this.ITEMs = new HashSet<ITEM>();
        }
    
        public int ID { get; set; }
        public bool Accepted { get; set; }
        public Nullable<float> Discount { get; set; }
        public int POType { get; set; }
        public System.DateTime ValidDate { get; set; }
        public Nullable<System.DateTime> FilledDate { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string ReceiptNo { get; set; }
        public string POName { get; set; }
        public Nullable<decimal> PrepaidAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int StatusID { get; set; }
        public Nullable<float> FixedRate { get; set; }
        public string Currency { get; set; }
        public bool Renewed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQ_BUDGET_CREDIT> ACQ_BUDGET_CREDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQ_BUDGET_DEBIT> ACQ_BUDGET_DEBIT { get; set; }
        public virtual ACQ_CURRENCY ACQ_CURRENCY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQ_ITEM> ACQ_ITEM { get; set; }
        public virtual ACQ_STATUS ACQ_STATUS { get; set; }
        public virtual ACQ_VENDOR ACQ_VENDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQ_PO_STATUS> ACQ_PO_STATUS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING> HOLDINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SER_ITEM> SER_ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SER_ROUTING> SER_ROUTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM> ITEMs { get; set; }
    }
}
