//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_BIBLIOGRAPHY_DETAIL
    {
        public int ID { get; set; }
        public string ItemIDs { get; set; }
        public Nullable<int> NORs { get; set; }
        public int Part_Index { get; set; }
        public Nullable<int> Position { get; set; }
        public string QString { get; set; }
        public string SQL { get; set; }
        public string GroupName { get; set; }
        public int GroupID { get; set; }
    }
}
