//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_DIC_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_DIC_LIST()
        {
            this.MARC_AUTHORITY_FIELD = new HashSet<MARC_AUTHORITY_FIELD>();
        }
    
        public string BrowseFile { get; set; }
        public Nullable<bool> ForPatron { get; set; }
        public Nullable<bool> ForStaff { get; set; }
        public short FieldSize { get; set; }
        public bool SystemDic { get; set; }
        public string DicTable { get; set; }
        public string IndexTable { get; set; }
        public string DicIDField { get; set; }
        public string DescriptionField { get; set; }
        public string IndexIDField { get; set; }
        public string CaptionField { get; set; }
        public string SearchFields { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public bool IsAuthority { get; set; }
        public bool IsClassification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARC_AUTHORITY_FIELD> MARC_AUTHORITY_FIELD { get; set; }
    }
}
