//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_AUTHORITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_AUTHORITY()
        {
            this.FIELD_AUTHORITY = new HashSet<FIELD_AUTHORITY>();
        }
    
        public int ID { get; set; }
        public int FormID { get; set; }
        public string Leader { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Code { get; set; }
        public string AccessEntry { get; set; }
        public string DisplayEntry { get; set; }
        public string Cataloguer { get; set; }
        public string Reviewer { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> NewRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIELD_AUTHORITY> FIELD_AUTHORITY { get; set; }
    }
}
