//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EDATA_MULTIMEDIA
    {
        public int ID { get; set; }
        public Nullable<byte> BitmapType { get; set; }
        public string ColorModel { get; set; }
        public Nullable<int> ImgWidth { get; set; }
        public Nullable<int> ImgHeight { get; set; }
        public Nullable<short> Xdpi { get; set; }
        public Nullable<short> Ydpi { get; set; }
        public Nullable<int> NoColorUsed { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public Nullable<int> BitRate { get; set; }
        public Nullable<float> Duration { get; set; }
        public string Genre { get; set; }
        public Nullable<int> PageCount { get; set; }
    }
}
