//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EDATA_AUDIO
    {
        public int ID { get; set; }
        public int FileSize { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public string FieldCode { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string URL { get; set; }
    
        public virtual ITEM ITEM { get; set; }
    }
}
