//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_PATRON_GROUP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CIR_PATRON_GROUP()
        {
            this.CIR_PATRON = new HashSet<CIR_PATRON>();
            this.HOLDING_LOCATION = new HashSet<HOLDING_LOCATION>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int InLibraryQuota { get; set; }
        public int LoanQuota { get; set; }
        public int HoldQuota { get; set; }
        public int HoldTurnTimeOut { get; set; }
        public int Priority { get; set; }
        public int ILLQuota { get; set; }
        public int AccessLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIR_PATRON> CIR_PATRON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_LOCATION> HOLDING_LOCATION { get; set; }
    }
}
