//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_RENEW
    {
        public int ID { get; set; }
        public Nullable<int> CirLoanID { get; set; }
        public Nullable<int> CirLoanHisID { get; set; }
        public Nullable<System.DateTime> OverDueDateOld { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public Nullable<System.DateTime> OverDueDateNew { get; set; }
    }
}
