//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIR_OPEN_HOUR
    {
        public Nullable<byte> WeekDay { get; set; }
        public string Close1 { get; set; }
        public string Close2 { get; set; }
        public string Open1 { get; set; }
        public string Open2 { get; set; }
        public int LocationID { get; set; }
    
        public virtual HOLDING_LOCATION HOLDING_LOCATION { get; set; }
    }
}
