//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASSIFICATION_LINK_TYPES
    {
        public int ID { get; set; }
        public Nullable<int> ReverseID { get; set; }
        public string Type { get; set; }
    }
}
