//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EDELIV_PAYMENT
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Currency { get; set; }
        public int Rate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> RequestID { get; set; }
        public string Note { get; set; }
        public bool Paid { get; set; }
        public int PaidID { get; set; }
    
        public virtual EDELIV_REQUEST EDELIV_REQUEST { get; set; }
        public virtual EDELIV_USER EDELIV_USER { get; set; }
    }
}
