//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLDING_TO_REMOVE_EXCEL
    {
        public int ID { get; set; }
        public string CopyNumber { get; set; }
        public string LiquidCode { get; set; }
        public string Reason { get; set; }
    }
}
