//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLDING_LIBRARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOLDING_LIBRARY()
        {
            this.HOLDINGs = new HashSet<HOLDING>();
            this.HOLDING_INVENTORY = new HashSet<HOLDING_INVENTORY>();
            this.HOLDING_SHELF_SCHEMA = new HashSet<HOLDING_SHELF_SCHEMA>();
            this.HOLDING_LOCATION = new HashSet<HOLDING_LOCATION>();
            this.FPT_SP_SPECIALIZED_STORE = new HashSet<FPT_SP_SPECIALIZED_STORE>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool LocalLib { get; set; }
        public string Address { get; set; }
        public string AccessEntry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING> HOLDINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_INVENTORY> HOLDING_INVENTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_SHELF_SCHEMA> HOLDING_SHELF_SCHEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_LOCATION> HOLDING_LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FPT_SP_SPECIALIZED_STORE> FPT_SP_SPECIALIZED_STORE { get; set; }
    }
}
