//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOLDING_LOCATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOLDING_LOCATION()
        {
            this.CIR_LOAN = new HashSet<CIR_LOAN>();
            this.HOLDINGs = new HashSet<HOLDING>();
            this.HOLDING_INVENTORY = new HashSet<HOLDING_INVENTORY>();
            this.HOLDING_SHELF_SCHEMA = new HashSet<HOLDING_SHELF_SCHEMA>();
            this.SER_ROUTING = new HashSet<SER_ROUTING>();
            this.SER_COPY = new HashSet<SER_COPY>();
            this.CIR_PATRON_GROUP = new HashSet<CIR_PATRON_GROUP>();
            this.SYS_EVENT_GROUP = new HashSet<SYS_EVENT_GROUP>();
            this.SYS_USER = new HashSet<SYS_USER>();
            this.SYS_USER1 = new HashSet<SYS_USER>();
            this.SYS_USER2 = new HashSet<SYS_USER>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LibID { get; set; }
        public string Symbol { get; set; }
        public bool Status { get; set; }
        public Nullable<int> MaxNumber { get; set; }
        public string CodeLoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIR_LOAN> CIR_LOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING> HOLDINGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_INVENTORY> HOLDING_INVENTORY { get; set; }
        public virtual HOLDING_LIBRARY HOLDING_LIBRARY { get; set; }
        public virtual CIR_OPEN_HOUR CIR_OPEN_HOUR { get; set; }
        public virtual HOLDING_LOCATION_SCHEMA HOLDING_LOCATION_SCHEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOLDING_SHELF_SCHEMA> HOLDING_SHELF_SCHEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SER_ROUTING> SER_ROUTING { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SER_COPY> SER_COPY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIR_PATRON_GROUP> CIR_PATRON_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_EVENT_GROUP> SYS_EVENT_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER> SYS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER> SYS_USER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER> SYS_USER2 { get; set; }
    }
}
