//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_INCOMING_REQUESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILL_INCOMING_REQUESTS()
        {
            this.ILL_INCOMING_REQUESTS_LOG = new HashSet<ILL_INCOMING_REQUESTS_LOG>();
        }
    
        public bool Alert { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<byte> ChargeableUnits { get; set; }
        public Nullable<System.DateTime> CheckedInDate { get; set; }
        public Nullable<System.DateTime> CheckedOutDate { get; set; }
        public byte CopyrightCompliance { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyCode1 { get; set; }
        public string CurrencyCode2 { get; set; }
        public string CurrencyCode3 { get; set; }
        public Nullable<byte> DelivConditionID { get; set; }
        public byte DelivMode { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string EDelivMode { get; set; }
        public string EDelivTSAddr { get; set; }
        public string EmailReplyAddress { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> InsuredForCost { get; set; }
        public string InternalRefNumber { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<byte> LoanTypeID { get; set; }
        public Nullable<decimal> MaxCost { get; set; }
        public Nullable<byte> Medium { get; set; }
        public Nullable<System.DateTime> NeedBeforeDate { get; set; }
        public string Note { get; set; }
        public string PatronID { get; set; }
        public string PatronName { get; set; }
        public string PatronStatus { get; set; }
        public bool PaymentProvided { get; set; }
        public Nullable<byte> PaymentType { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool ReciprocalAgreement { get; set; }
        public bool Renewable { get; set; }
        public Nullable<short> Renewals { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequesterID { get; set; }
        public string RequestID { get; set; }
        public Nullable<System.DateTime> RespondDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<decimal> ReturnInsuranceCost { get; set; }
        public Nullable<byte> ReturnLocID { get; set; }
        public byte ServiceType { get; set; }
        public Nullable<System.DateTime> ShippedDate { get; set; }
        public string IssueID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string Title { get; set; }
        public Nullable<byte> TransportationModeID { get; set; }
        public bool WillPayFee { get; set; }
    
        public virtual ILL_ITEM_TYPES ILL_ITEM_TYPES { get; set; }
        public virtual ILL_LIBRARIES ILL_LIBRARIES { get; set; }
        public virtual ILL_REQUEST_STATUS ILL_REQUEST_STATUS { get; set; }
        public virtual ITEM ITEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_INCOMING_REQUESTS_LOG> ILL_INCOMING_REQUESTS_LOG { get; set; }
    }
}
