//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_LOCAL_LIBRARY_E_ADDRESSES
    {
        public string EDelivMode { get; set; }
        public string EDelivTSAddr { get; set; }
        public int ID { get; set; }
    }
}
