//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_LIBRARIES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ILL_LIBRARIES()
        {
            this.ILL_INCOMING_REQUESTS = new HashSet<ILL_INCOMING_REQUESTS>();
            this.ILL_INCOMING_REQUESTS_LOG = new HashSet<ILL_INCOMING_REQUESTS_LOG>();
            this.ILL_OUTGOING_REQUESTS_DENIED = new HashSet<ILL_OUTGOING_REQUESTS_DENIED>();
            this.ILL_OUTGOING_REQUESTS = new HashSet<ILL_OUTGOING_REQUESTS>();
            this.ILL_OUTGOING_REQUESTS_LOG = new HashSet<ILL_OUTGOING_REQUESTS_LOG>();
        }
    
        public string AccountNumber { get; set; }
        public string BillDelivBox { get; set; }
        public string BillDelivCity { get; set; }
        public string BillDelivCode { get; set; }
        public Nullable<byte> BillDelivCountry { get; set; }
        public string BillDelivName { get; set; }
        public string BillDelivRegion { get; set; }
        public string BillDelivStreet { get; set; }
        public string BillDelivXAddr { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Dublicate { get; set; }
        public string EDelivMode { get; set; }
        public string EDelivTSAddr { get; set; }
        public string EmailReplyAddress { get; set; }
        public byte EncodingScheme { get; set; }
        public int ID { get; set; }
        public string LibraryName { get; set; }
        public string LibrarySymbol { get; set; }
        public bool LocalLib { get; set; }
        public string Note { get; set; }
        public string PostDelivBox { get; set; }
        public string PostDelivCity { get; set; }
        public string PostDelivCode { get; set; }
        public Nullable<byte> PostDelivCountry { get; set; }
        public string PostDelivName { get; set; }
        public string PostDelivRegion { get; set; }
        public string PostDelivStreet { get; set; }
        public string PostDelivXAddr { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_INCOMING_REQUESTS> ILL_INCOMING_REQUESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_INCOMING_REQUESTS_LOG> ILL_INCOMING_REQUESTS_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_OUTGOING_REQUESTS_DENIED> ILL_OUTGOING_REQUESTS_DENIED { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_OUTGOING_REQUESTS> ILL_OUTGOING_REQUESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ILL_OUTGOING_REQUESTS_LOG> ILL_OUTGOING_REQUESTS_LOG { get; set; }
    }
}
