//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_Z3950_DBS
    {
        public int ID { get; set; }
        public int ServerID { get; set; }
        public string DBName { get; set; }
        public string Description { get; set; }
    
        public virtual ILL_Z3950_SERVERS ILL_Z3950_SERVERS { get; set; }
    }
}
