//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_OUTGOING_REQUESTS_DENIED
    {
        public string ID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public Nullable<System.DateTime> RespondDate { get; set; }
        public int ResponderID { get; set; }
        public byte ReasonID { get; set; }
        public string Note { get; set; }
    
        public virtual ILL_LIBRARIES ILL_LIBRARIES { get; set; }
    }
}
