//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ILL_LOCAL_LIBRARY_ADDRESSES
    {
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> CountryID { get; set; }
        public int ID { get; set; }
        public string POBox { get; set; }
        public string PostCode { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string XAddress { get; set; }
    }
}
