//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARC_AUTHORITY_WS_DETAIL
    {
        public int FormID { get; set; }
        public string FieldCode { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public string DefaultValue { get; set; }
        public bool IstextBox { get; set; }
        public string DefaultIndicators { get; set; }
    
        public virtual MARC_AUTHORITY_WORKSHEET MARC_AUTHORITY_WORKSHEET { get; set; }
    }
}
