//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MARC_BIB_FIELD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MARC_BIB_FIELD()
        {
            this.MARC_BIB_INDICATOR = new HashSet<MARC_BIB_INDICATOR>();
        }
    
        public int ID { get; set; }
        public Nullable<int> AuthorityID { get; set; }
        public bool Mandatory { get; set; }
        public Nullable<int> FunctionID { get; set; }
        public bool Coded { get; set; }
        public int Length { get; set; }
        public string Description { get; set; }
        public string Indicators { get; set; }
        public string VietIndicators { get; set; }
        public int FieldTypeID { get; set; }
        public bool Repeatable { get; set; }
        public Nullable<int> LinkTypeID { get; set; }
        public string FieldCode { get; set; }
        public int BlockID { get; set; }
        public string VietFieldName { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> DicID { get; set; }
        public string ParentFieldCode { get; set; }
        public bool IsMARCField { get; set; }
        public Nullable<bool> NeedHelp { get; set; }
        public Nullable<int> ClassificationID { get; set; }
    
        public virtual MARC_BIB_BLOCK MARC_BIB_BLOCK { get; set; }
        public virtual MARC_FUNCTION MARC_FUNCTION { get; set; }
        public virtual MARC_LINK_TYPE MARC_LINK_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MARC_BIB_INDICATOR> MARC_BIB_INDICATOR { get; set; }
    }
}
