//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGULARITY_OUT
    {
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string PATRONID { get; set; }
        public Nullable<int> LOCATIONOUT_ID { get; set; }
        public string NOTE { get; set; }
    }
}
