//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_USER_RIGHT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_USER_RIGHT()
        {
            this.SYS_USER_RIGHT_DETAIL = new HashSet<SYS_USER_RIGHT_DETAIL>();
        }
    
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public string Right { get; set; }
        public bool IsBasic { get; set; }
    
        public virtual SYS_MODULE SYS_MODULE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_USER_RIGHT_DETAIL> SYS_USER_RIGHT_DETAIL { get; set; }
    }
}
